### ISSUE TITLE
V8.1 - "auto-start/stop" feature not working anymore

### ISSUE THREAD

**Issue by Pierrodu21** [jmcollin78/versatile_thermostat#1251]
## Version of the custom_component
--> 8.0.1

## Configuration

My VTherm attributes are the following:
```
hvac_modes:
  - "off"
  - fan_only
  - heat
  - cool
  - heat_cool
  - dry
min_temp: 10
max_temp: 30
target_temp_step: 0.5
fan_modes:
  - auto
  - quiet
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
preset_modes:
  - away
  - boost
  - none
swing_modes:
  - stop
  - swing
  - windnice
swing_horizontal_modes:
  - stop
  - swing
current_temperature: 20
temperature: 17
fan_mode: auto
preset_mode: none
swing_mode: swing
swing_horizontal_mode: swing
friendly_name: Salle à manger Room Temperature
supported_features: 953
```

My VTherm attributes are the following:
```
hvac_modes:
  - "off"
  - fan_only
  - heat
  - cool
  - heat_cool
  - dry
min_temp: 10
max_temp: 30
target_temp_step: 0.5
fan_modes:
  - auto
  - quiet
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
preset_modes:
  - away
  - boost
  - none
swing_modes:
  - stop
  - swing
  - windnice
swing_horizontal_modes:
  - stop
  - swing
current_temperature: 17
temperature: 16
fan_mode: auto
preset_mode: none
swing_mode: swing
swing_horizontal_mode: swing
friendly_name: Chambre de Tom Room Temperature
supported_features: 953
```

My VTherm attributes are the following:
```
hvac_modes:
  - "off"
  - fan_only
  - heat
  - cool
  - heat_cool
  - dry
min_temp: 10
max_temp: 30
target_temp_step: 0.5
fan_modes:
  - auto
  - quiet
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
preset_modes:
  - away
  - boost
  - none
swing_modes:
  - stop
  - swing
  - windnice
swing_horizontal_modes:
  - stop
  - swing
current_temperature: 21
temperature: 16
fan_mode: auto
preset_mode: none
swing_mode: swing
swing_horizontal_mode: swing
friendly_name: Chambre des parents Room Temperature
supported_features: 953
```

My VTherm attributes are the following:
```
hvac_modes:
  - "off"
  - fan_only
  - heat
  - cool
  - heat_cool
  - dry
min_temp: 10
max_temp: 30
target_temp_step: 0.5
fan_modes:
  - auto
  - quiet
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
preset_modes:
  - away
  - boost
  - none
swing_modes:
  - stop
  - swing
  - windnice
swing_horizontal_modes:
  - stop
  - swing
current_temperature: 20
temperature: 19
fan_mode: auto
preset_mode: none
swing_mode: swing
swing_horizontal_mode: swing
friendly_name: Chambre de Martin Room Temperature
supported_features: 953
```

## Describe the bug
I think I've had the same problem since upgrading to version 8 with the “auto-start/stop” feature.

At the moment, Versatile Thermostat is no longer working in my home. I have to start my various air conditioning units manually, and in some cases, Versatile Thermostat takes over to control the heating correctly but then doesn't turn the units off, so I have to do that manually as well. This morning, it didn't work at all, so I had to turn on, manage, and then turn off my four air conditioning units manually.

What information can I give you to help you understand whether this is due to incorrect operation on my part or a problem with the “auto-start/stop” function?

I should point out that I had no problems before version 8 and that, like manudebouc, it used to be almost instantaneous before. For example, in the morning at 8:30 a.m., I programmed the devices to switch to “eco” mode and the four air conditioners turned off almost simultaneously at around 8:30 a.m. This morning, I had to turn off each device manually.

Here is what I found in the error logs:

```
Enregistreur: homeassistant.components.recorder.table_managers.event_data
Source: components/recorder/table_managers/event_data.py:43
intégration: Recorder (documentation, problèmes)
S'est produit pour la première fois: 08:15:13 (1 occurrence)
Dernier enregistrement: 08:15:13

Event is not JSON serializable: <Event versatile_thermostat_auto_start_stop_event[L]: type=start, name=Salle à manger, cause=Auto start conditions reached, hvac_mode=heat, saved_hvac_mode=heat, target_temperature=19.0, current_temperature=18.75, temperature_slope=-0.008, accumulated_error=3.07675108302083, accumulated_error_threshold=20, entity_id=climate.salle_a_manger, state_attributes=current_temperature=18.8, temperature=19.0, fan_mode=auto, hvac_action=idle, preset_mode=comfort, swing_mode=swing, swing_horizontal_mode=>: Type is not JSON serializable: VThermHvacMode
```

I'm trying to: use the "auto-start/stop" feature as before

And I expect: the "auto-start/stop" feature to start the devices when a change is needed in heating and then to top the devices after the temperature is obtained, or, the mode is switched to "eco" for instant

But I observe this: nothing seems to happen anymore

I read the documentation on the README.md file and I don't find any relevant information about this issue.

<img width="1078" height="795" alt="Image" src="https://github.com/user-attachments/assets/170cfc7f-55ae-4a6c-a606-e4cfeda54fac" />
<img width="536" height="913" alt="Image" src="https://github.com/user-attachments/assets/0fcde556-c8ff-4745-9a5a-29b6b0676f7b" />

**Comment by Pierrodu21** [comment]
I've just noticed a new error in the log:

```
Enregistreur: homeassistant.components.recorder.table_managers.event_data
Source: components/recorder/table_managers/event_data.py:43
intégration: Recorder (documentation, problèmes)
S'est produit pour la première fois: 15:37:12 (1 occurrence)
Dernier enregistrement: 15:37:12

Event is not JSON serializable: <Event versatile_thermostat_auto_start_stop_event[L]: type=start, name=Chambre de Martin, cause=Auto start conditions reached, hvac_mode=heat, saved_hvac_mode=heat, target_temperature=16.0, current_temperature=15.42, temperature_slope=-0.066, accumulated_error=1.1059965501302087, accumulated_error_threshold=20, entity_id=climate.chambre_de_martin, state_attributes=current_temperature=15.4, temperature=16.0, fan_mode=auto, hvac_action=idle, preset_mode=eco, swing_mode=swing, swing_horizontal_mode=>: Type is not JSON serializable: VThermHvacMode
```

I guess it's what's causing the issue here?

**Comment by madd0** [comment]
Not sure whether the JSON error would prevent the feature from working, but I created a PR that should fix it #1253

**Comment by Pierrodu21** [comment]
Thank you very much, finger crossed!

**Comment by jcmaison** [comment]
I have exactly the same issue. To narrow what I observed, the auto start/stop is working fine, except if a change in the vTherm attributes is applied during its stop phase. 

For instance, if vTherm is stopped by the auto-start/stop, and then a preset is changed, then everything seems frozen. Then disabling the auto-start/stop is awaking the vTherm. To be very detailed, the preset change is done by an automation (scheduler for me), and disabling the auto-start/stop function is done from the UI.

I also noticed the JSON error reported 14 minutes after the preset change.

**Comment by jmcollin78** [comment]
See #1253.
Let me know if it fixes your case. In V8.1 release which is coming today.

**Comment by jcmaison** [comment]
VT 8.1 running since 23-nov. UI card uodated as requested. **The issue is not fixed**.

What happend:
- 23-Nov 23:00 - From UI, set preset to Frost protection. Engage auto-start/stop. vTherm stops.
- 24-Nov 02:00 - From UI, set to Comfort. vTherm wakes-up as expected. Working fine. Auto-start/stop disabled from UI.
- 24-Nov 03:00 - From UI, set to Frost Protection preset. Auto-start/stop still disabled
- 24-Nov 03:30 - vTherm still running as expected. Auto-start/stop engaged from UI
- 24-Nov 06:00 - Scheduler set preset to Comfort. **vTherm did not wakes up as expected**
- 24-nov 07:30 - From UI, disengage auto-start/stop. vTherm wakes-up.

**Comment by Pierrodu21** [comment]
Hello! I think this specific issue has been fixed, as I no longer see this error appearing in the error logs. Thank you very much!

However, none of my air conditioners turned on by themselves yesterday after the upgrade to 8.1, and I didn't know what to do to get Versatile Thermostat working normally again.

This morning, I managed to restart the one in the dining room, and it now seems to be controlled by Versatile Thermostat again, as the little moon icon is displayed (which is normal during the day with my current settings).

What should I do about the others? How can I get Versatile Thermostat to regain control of them?

This is what I have right now:

<img width="1069" height="799" alt="Image" src="https://github.com/user-attachments/assets/ef52688a-91c6-46a0-bfc6-191c7de921b4" />
<img width="535" height="908" alt="Image" src="https://github.com/user-attachments/assets/690b2a86-659c-49f0-b5a7-d2bce62e67a0" />

**Comment by alocersheitzag** [comment]
Hello :)

On my side, the issue is still present with version 8.1.0.

My “over_climate” (air conditioning/heating units) are still trying to “heat colder” to go back down to their target value (when the house switches to ABS mode) instead of turning off.

I also noticed that during the night, my units struggled to reach their target temperature: they were often 0.5 °C below the target and did not try to heat more to compensate.

See photos.
Thank you in advance for your help, and congratulations on your amazing work! <3

<img width="328" height="312" alt="Image" src="https://github.com/user-attachments/assets/d945735c-1f62-4ff3-b95b-75385e2776ba" />
<img width="335" height="591" alt="Image" src="https://github.com/user-attachments/assets/9c39194e-2930-4375-bc11-f35b8a1f7f78" />

**Comment by Pierrodu21** [comment]
Indeed, it's not working like it used to... It's 12:15 p.m., the preset is on “Comfort.” The heating should be on, but... nothing! However, I don't see any errors in the error logs, so I don't know what else to do at the moment!

<img width="536" height="413" alt="Image" src="https://github.com/user-attachments/assets/f11d5a88-4e2d-4ed1-9a1e-f98a58834e90" />

**Comment by defunes43** [comment]
Can confirm the issue is still here.

The event is fired as expected:

```
2025-11-24 10:04:52.178 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] --------------------> NEW EVENT: VersatileThermostat-Régulation Température Salon - Periodical control cycle started --------------------------------------------------------------
2025-11-24 10:04:52.180 INFO (MainThread) [custom_components.versatile_thermostat.auto_start_stop_algorithm] AutoStartStopDetectionAlgorithm-Régulation Température Salon - auto-start/stop: We need to stop, there is no need for heating for a long time.
2025-11-24 10:04:52.187 INFO (MainThread) [custom_components.versatile_thermostat.feature_auto_start_stop_manager] AutoStartStopManager-Régulation Température Salon - VTherm should be OFF due to auto-start-stop conditions
2025-11-24 10:04:52.187 INFO (MainThread) [custom_components.versatile_thermostat.const] VersatileThermostat-Régulation Température Salon - Sending event EventType.AUTO_START_STOP_EVENT with data: {'type': 'stop', 'name': 'Régulation Température Salon', 'cause': 'Auto stop conditions reached', 'hvac_mode': 'off', 'saved_hvac_mode': 'heat', 'target_temperature': 20.0, 'current_temperature': 20.8, 'temperature_slope': 0.029, 'accumulated_error': -10, 'accumulated_error_threshold': 10}
2025-11-24 10:04:52.188 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Régulation Température Salon - Auto stop state changed from False to True
```
`is_auto_stop_detected` is switched to `true` as expected, but the `hvac_mode` is not set to off.

**Comment by jmcollin78** [comment]
> Hello! I think this specific issue has been fixed, as I no longer see this error appearing in the error logs. Thank you very much!
> 
> However, none of my air conditioners turned on by themselves yesterday after the upgrade to 8.1, and I didn't know what to do to get Versatile Thermostat working normally again.
> 
> This morning, I managed to restart the one in the dining room, and it now seems to be controlled by Versatile Thermostat again, as the little moon icon is displayed (which is normal during the day with my current settings).
> 
> What should I do about the others? How can I get Versatile Thermostat to regain control of them?
> 
> This is what I have right now:
> 
> <img alt="Image" width="1069" height="799" src="https://private-user-images.githubusercontent.com/58418348/518039877-ef52688a-91c6-46a0-bfc6-191c7de921b4.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQwMjA4OTIsIm5iZiI6MTc2NDAyMDU5MiwicGF0aCI6Ii81ODQxODM0OC81MTgwMzk4NzctZWY1MjY4OGEtOTFjNi00NmEwLWJmYzYtMTkxYzdkZTkyMWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTI0VDIxNDMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZTc0ODY2NTE1MzZmN2Y2MDQzOGQzY2FmYmFiNjc5N2I1OTY3YWZhMmNjNzEzNTYwZmZlYjIyYzdlYmViMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MUtVpOm-2lcYE8h_Vgs6rFLUBDz8Iu055z-VSgQXFrc"> <img alt="Image" width="535" height="908" src="https://private-user-images.githubusercontent.com/58418348/518039878-690b2a86-659c-49f0-b5a7-d2bce62e67a0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQwMjA4OTIsIm5iZiI6MTc2NDAyMDU5MiwicGF0aCI6Ii81ODQxODM0OC81MTgwMzk4NzgtNjkwYjJhODYtNjU5Yy00OWYwLWI1YTctZDJiY2U2MmU2N2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTI0VDIxNDMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMmE0YjM1ZDczYjcyYWU3NGMwY2NmODA4ZjUyOWZiNjM3YzBkM2E1OGQzM2NjMGJiNDI0MmFmZTUxY2M1NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h0Ih3_77XhGwXCymti8Lc_yP3V06LHri86kUVrdSnMo">

Hello, your VTherm are not stopped with auto-start/stop feature. If there were, you should have a moon icon of the card. Only the salle à mange have it.

If you click on the information icon, you should be able to see why your VTherm are off. I'm pretty sure, there are closed manually. More information here: https://github.com/jmcollin78/versatile-thermostat-ui-card?tab=readme-ov-file#display-some-messages

For information, in the release note of the V8 it was written that you have to control the mode of your Vtherm. Do you have done this when installing the V8 ? This is maybe the source of your issue. If yes, just click on the flame to activate the Vtherm.

**Comment by jmcollin78** [comment]
> Indeed, it's not working like it used to... It's 12:15 p.m., the preset is on “Comfort.” The heating should be on, but... nothing! However, I don't see any errors in the error logs, so I don't know what else to do at the moment!
> 
> <img alt="Image" width="536" height="413" src="https://private-user-images.githubusercontent.com/58418348/518074279-f11d5a88-4e2d-4ed1-9a1e-f98a58834e90.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQwMjEzMTUsIm5iZiI6MTc2NDAyMTAxNSwicGF0aCI6Ii81ODQxODM0OC81MTgwNzQyNzktZjExZDVhODgtNGUyZC00ZWQxLTlhMWUtZjk4YTU4ODM0ZTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTI0VDIxNTAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NzU5MzYyNGY5NjQzNTM0MTMxOTM2MjI5Njk4M2ZhOWM2M2ZlMzBjYWI0YTVlMTdmZGI1MzI5YzJhYWJlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EBToEUR_MHsunVCRctV_VC3CLdic4PlnLtZskhgrBE4">

Click on the information icon please and what do you see ?

**Comment by jmcollin78** [comment]
To all, please read this: More information here: https://github.com/jmcollin78/versatile-thermostat-ui-card?tab=readme-ov-file#display-some-messages and this: https://github.com/jmcollin78/versatile-thermostat-ui-card?tab=readme-ov-file#update-of-underlying-scheduled

I want to be sure that your VTherm are not just turned off manually.

Check also the attributes of the Vtherm at this section:
```
auto_start_stop_manager:
  auto_start_stop_enable: true
  auto_start_stop_level: auto_start_stop_medium
  auto_start_stop_dtmin: 15
  auto_start_stop_accumulated_error: -5
  auto_start_stop_accumulated_error_threshold: 5
  auto_start_stop_last_switch_date: "2025-11-24T22:45:52.780898+01:00"
  is_auto_stop_detected: true
```
You should have `auto_start_stop_enable: true` and `is_auto_stop_detected: true`to be sure that your VTherm is stopped by the auto-start/stop feature.

At home I use it every day and it works fine.

Thank you for your help !

**Comment by jmcollin78** [comment]
I think I ve got the same case tonight. It should definitively heat :

<img width="312" height="233" alt="Image" src="https://github.com/user-attachments/assets/bde8bff2-efa8-47ad-8c46-82c73ec0281d" />

**Comment by jcmaison** [comment]
Hello @jmcollin78,

Current state:

<img width="864" height="740" alt="Image" src="https://github.com/user-attachments/assets/4d4b8d7f-622b-4d5a-b1cf-4c364e95ee38" />

auto_start_stop_manager:
  auto_start_stop_enable: true
  auto_start_stop_level: auto_start_stop_medium
  auto_start_stop_dtmin: 15
  auto_start_stop_accumulated_error: -1.9247204319999995
  auto_start_stop_accumulated_error_threshold: 5
  auto_start_stop_last_switch_date: "2025-11-24T23:23:11.630515+01:00"
  is_auto_stop_detected: true

**Comment by jcmaison** [comment]
Strange. At midnight the scheduler changes the preset to frost and the vTherm was awkened in Heat mode:

<img width="864" height="740" alt="Image" src="https://github.com/user-attachments/assets/5d6009fb-5ea4-47ae-8a3b-2d151f1c5784" />

**Comment by jmcollin78** [comment]
Hello,

bug is reproduced. The better is certainly to uncheck the auto-start/stop button on your VTherm waiting for a fix.

Thanks for the report !

**Comment by wallb35** [comment]
Same issue here, looks like auto start/stop mode doesn't wake up after a long stop period.

**Comment by jmcollin78** [comment]
Hello All,

Can you please test this bug fix: https://github.com/jmcollin78/versatile_thermostat/releases/tag/8.1.1.beta1

You have to force the release version in HACS to install a beta release. I can no more reproduce the bug in my test environment.
I waill install it also to see the behavior at night.

The change is very small and just force the update of the VTherm state when auto-start/stop is needed or no more needed.

**Comment by jcmaison** [comment]
v8.1.1 beta 1 installed. Let you know in a few hours.

**Comment by jcmaison** [comment]
Nope, does not seem to work: 

Initial state: 

<img width="479" height="339" alt="Image" src="https://github.com/user-attachments/assets/7644021d-68f0-4135-876e-9b6193ef566b" />

Boost mode launched from the UI:

<img width="491" height="338" alt="Image" src="https://github.com/user-attachments/assets/9206e853-c277-4193-8f5d-2fbd8c2763c7" />

I had to disengage the auto-start/stop to get vTherm swithching to heating:

<img width="479" height="337" alt="Image" src="https://github.com/user-attachments/assets/7cb96e3e-0e90-4728-84dd-86974bcf69c4" />

Should I test a different way ? Provide any attributes ?

**Comment by wallb35** [comment]
trying will see tomorrow morning ;)

**Comment by Pierrodu21** [comment]
8.1.1.beta1 installed here too, it seems better for the moment, will see tomorrow morning!

**Comment by jmcollin78** [comment]
> Nope, does not seem to work:
> 
> Initial state:
> 
> <img alt="Image" width="479" height="339" src="https://private-user-images.githubusercontent.com/191030370/518784972-7644021d-68f0-4135-876e-9b6193ef566b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQxMDQ0MTIsIm5iZiI6MTc2NDEwNDExMiwicGF0aCI6Ii8xOTEwMzAzNzAvNTE4Nzg0OTcyLTc2NDQwMjFkLTY4ZjAtNDEzNS04NzZlLTliNjE5M2VmNTY2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyNVQyMDU1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWJlYjQ4MWVkYmFlOGJmOTMyODIwZjFhYzgwMmRkNTk5ZGU2YmQ1YzRmYTJiNDlmYTAzMjg4ZGMwZWQ2YzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5n6tU3FwRzZVCLtuTftjv2vWyRM8iraEAzgSwA5FO1Y">
> Boost mode launched from the UI:
> 
> <img alt="Image" width="491" height="338" src="https://private-user-images.githubusercontent.com/191030370/518785223-9206e853-c277-4193-8f5d-2fbd8c2763c7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQxMDQ0MTIsIm5iZiI6MTc2NDEwNDExMiwicGF0aCI6Ii8xOTEwMzAzNzAvNTE4Nzg1MjIzLTkyMDZlODUzLWMyNzctNDE5My04ZjVkLTJmYmQ4YzI3NjNjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyNVQyMDU1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWE2YzZjNDI3OTQwODZiYTJiNWZmNzZkZDUxOGM5ZWJhMWQyMTBlNTcxYmFkZmE1MDZkZjllNjljNTdhNzE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GYj67HKfyMJJru1YmwQwFPlzRlSobC0KuCqmqJ0Bkeg">
> I had to disengage the auto-start/stop to get vTherm swithching to heating:
> 
> <img alt="Image" width="479" height="337" src="https://private-user-images.githubusercontent.com/191030370/518786171-7cb96e3e-0e90-4728-84dd-86974bcf69c4.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQxMDQ0MTIsIm5iZiI6MTc2NDEwNDExMiwicGF0aCI6Ii8xOTEwMzAzNzAvNTE4Nzg2MTcxLTdjYjk2ZTNlLTBlOTAtNDcyOC04NGRkLTg2OTc0YmNmNjljNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyNVQyMDU1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2JhOWI2MGZmMzM2ODFjY2YzYTc3N2Y4ZjUxOGE0MGIzOGEyZWYzNWYwMDA3NjE1OWYyODk2NzZiYmQ2N2UxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ILQcwzCUNpd3iAgYRn4dQ3v1zmZROWkEJ7vI-CYDtUY">
> Should I test a different way ? Provide any attributes ?

What is wrong here in your opinion ? The auto-start/stop will not disable itself with a difference of temperature of 0.5 only. There is threshold and duration to avoid too much swicth which is not good for you PAC.

**Comment by jcmaison** [comment]
You are right. Sorry for the post. I will wait tomorrow morning anyway.

**Comment by wallb35** [comment]
hello, it’s ok for me all night and this morning ;)

**Comment by Pierrodu21** [comment]
Hello! I’m not sure yet, because it’s a lot less cold here and my preset are close to the current temperatures in the different rooms, so none devices are heating this morning but it’s not cold in the house… will check again later!

**Comment by jcmaison** [comment]
It’s ok also for me. Scheduler changed presets and V therms woke up accordingly.

**Comment by nicolinuxfr** [comment]
I thought it was OK for me, but just now the heating stopped for no apparent reason. The card is telling me the auto-stop feature is to blame. There is a big difference of temperature, so it should not have stopped the heating.

<img width="488" height="334" alt="Image" src="https://github.com/user-attachments/assets/a24cce9d-7f1f-4595-b3de-fa4415cc9f49" />
<img width="494" height="337" alt="Image" src="https://github.com/user-attachments/assets/32b151b4-f787-4d13-9c66-46ee3042bd3c" />

**Comment by Pierrodu21** [comment]
Hello again!

8.1.1.beta1 installed here since almost a full day now, it seems partially fixed...

I mean, Versatile Thermostat can switch on and off again my air conditioners, but, I have the same behavior than nicolinuxfr at the moment:

<img width="1100" height="800" alt="Image" src="https://github.com/user-attachments/assets/0e61dbaf-7a43-4ea4-b76d-51730367b34f" />

As you can see, Versatile Thermostat correctly switch on the two kid's bedroom, but didn't switch on the dining room even if there is a 1,3 degrees difference between the requested temperature ans the current temperature...

Can you tell us if it's the new "normal" with the v8 or if there is still an issue here?

**Comment by nicolinuxfr** [comment]
One more issue I noticed a couple of times since installing the new version : instead of starting the heating, my heat pump was set to cooling ! 🥶 I've never seen this behavior before 8.x.

**Comment by jcmaison** [comment]
In my opinion, the fix is working. Thank you.

**Comment by nicolinuxfr** [comment]
Definitely not working this morning for me, unfortunately… I took this these three screenshots this morning and the only thing *I* did between them is clicking the Auto-start/stop switch. As I forgot to take one, let me explain for clarity.

Waking up, I had this : 

<img width="603" height="1311" alt="Image" src="https://github.com/user-attachments/assets/9c090e7f-e348-473d-84fb-74b3145db289" />

I clicked the switch once and the heatpump went into cooling mode for some reason : 

<img width="603" height="1311" alt="Image" src="https://github.com/user-attachments/assets/03367b4d-bc52-4598-b830-04afbe07dc6c" />

I clicked twice (after the first one, I think it was gray again, I was just waking up and not paying enough attention, sorry) and it was on heating as needed :

<img width="603" height="1311" alt="Image" src="https://github.com/user-attachments/assets/d3cf8848-ede8-49be-bcd7-af6efdb72647" />

Let me know if you need more details on my setup or something else.

**Comment by wallb35** [comment]
some bug still hidding, this morning one schedule woke up the second one doesn’t.

![Image](https://github.com/user-attachments/assets/a89f2e57-b640-4510-ab73-598fec34be39)

at 6:30AM the schedule should have woke up my PAC, waited 5mn, then tried to click on heat : doesn’t work, then click on comfort and the PAC woke up.

**Comment by wallb35** [comment]
I also have to reload my versatile RDC integration at 8:44AM in order to detect absence of motion :/

**Comment by jmcollin78** [comment]
Hello, I fix also an issue #1274 which can interact with this issue. I will publish a release for the both issue. All my tests are now ok.

Thank you for your report. Of course if you have still some issues you can continue to post here (or in a new issue). When I will merge, it closes automatically the issue.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/8.1.1

**Comment by wallb35** [comment]
hello, I’m sorry it’s not fixed at all :/

**Comment by jmcollin78** [comment]
> hello, I’m sorry it’s not fixed at all :/

I have answer you directly in another thread if i'm not wrong.
